# Develop override settings

url: http://localhost:4000

analytics:
  provider: false

posts:
  output: false
  permalink: /:collection/:path/

comments:
  disqus:
    shortname            : "mmistakes-dev"

sass:
  style: expanded
